---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-id: my-kubernetes-component
  name: my-kubernetes-component
spec:
  type: service
  lifecycle: production
  owner: group:krypton
