---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kind
  annotations:
    'kubernetes.io/url': https://127.0.0.1:34085
    'kubernetes.io/authProvider': serviceAccount
    'kubernetes.io/skipTLSVerify': 'true'
    'kubernetes.io/serviceAccountToken': ${K8S_TOKEN}
    'kubernetes.io/caData': 'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1ETXpNVEV5TXpRME5sb1hEVE16TURNeU9ERXlNelEwTmxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS2x0Ci8zbmdQRHhCeWgxRE5sTDVWWHJFZk13ak1NU0xOaXlJVHN1NzNUcGNsajlDYjNNQkVSdmRMcVhrNjBlejdrajcKV2oxZWFscFlBcXI4ZUhqVzArS29GanYzZ25mcmtlWEFIVFc5QWtydXpZUzVGOXVVUU4reE9KRm1rY2hzUVNNMwo4Y01CWE1qRytMOUZLNW5XTG8rQlFWMGV1VUFkUUZaVSs5Tm9BcTVBcWtCeEd0bFRqTWhpd2lydEw5c3dtR1dsCm1lNGp0R3FHc2x6b3UzdHdvbjA5Y3RlME1WTTBqMTRxVnNrK00yNiszQ0dLWFZBOVhSNWN4Z0Z1YkI5WVZBblcKRFpNaWRwaFZnQ0J3THcxUWVjekZCMFFjeS82MEVyNWpjbzdrSmM3RGNhWjExU3YvcTI1cG9ZemlySjBYeFRXZQpCdG1WVHNTUXoxNkozbGhYUUVjQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZJanBQOFlEMWdtK0Z1cDNZQ1hsWUxSQzVvSkdNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBS0hZNHpRT2dXTE1od0FLUGhPZwpvZnhmSlJaTVN6TXlkZ3JvLzhXVEFCZWNhNllCRnp4WHNWOW1YK3oxMG43TmZIcHlsdTVLZC8rTSs3ajdpYkNTCm45SGFJMS8wc05nOFVXVFJSaEY0b1VFcWw1eUVQMjdyb3VWbmVsV2lWYVpsYnovOCtEeFBFYjJ1T3VoTVBxWCsKVjNoTGRtN2I0dGEvNUg5bTRkbml4b3o2b0ExclloRmhkVHp5d1RwS2h6NWxvRlYyN2ZLK2REVVdCRDNLTFRnVgpwL2JQNTVUS0NBTG43L21GektlUkMxMEh6UHNodWtNRlFOM2l0dVV1REFIMERXTjRoZEMwcmZ5alZoQ0RPbkkyCkhJTUV1ei92blhCR1pBOVhkVVdOby9qWGNIbnk0Ukg2N25hd0FONkxWTXYxN25xK0l5VmZ4K3krM1dXblBlUVAKWmQwPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=='
    'kubernetes.io/skip-metrics-lookup': 'true'
spec:
  type: kubernetes-cluster
  owner: group:krypton
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-id: kind
  name: my-kubernetes-component
spec:
  type: service
  lifecycle: production
  owner: group:krypton
