---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kind-k8s
  annotations:
    'kubernetes.io/api-server': 'http://localhost:35495'
    'kubernetes.io/auth-provider': 'serviceAccount'
    'kubernetes.io/serviceAccountToken': '${K8S_TOKEN}'
    'kubernetes.io/skip-tls-verify': 'true'
    'kubernetes.io/skip-metrics-lookup': 'true'
spec:
  type: kubernetes-cluster
  owner: group:krypton
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-id: my-kubernetes-component
  name: my-kubernetes-component
spec:
  type: service
  lifecycle: production
  owner: group:krypton
