---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kind
  annotations:
    'kubernetes.io/url': https://127.0.0.1:34085
    'kubernetes.io/authProvider': serviceAccount
    'kubernetes.io/skipTLSVerify': 'true'
    'kubernetes.io/serviceAccountToken': ${K8S_TOKEN}
    'kubernetes.io/skip-metrics-lookup': 'true'
spec:
  type: kubernetes-cluster
  owner: group:krypton
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kube-dns
  annotations:
    'backstage.io/kubernetes-id': kind
    'backstage.io/kubernetes-namespace': kube-system
    'backstage.io/kubernetes-label-selector': 'k8s-app=kube-dns'
spec:
  type: service
  lifecycle: production
  owner: group:krypton
